@controller=http://localhost/wajibpajak/kategori

GET {{controller}}/get HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
  "kategori": "Rumah Makan"
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "id": "1",
  "kategori": "Kios"
}

###

DELETE {{controller}}/delete/2 HTTP/1.1